### ISSUE TITLE
Adding seed data

### ISSUE THREAD

**Issue by shlok007** [Small-Start/JSS-Free-Lancers#2]

**Comment by aayusharora** [comment]
@shlok007 , Please provide a valid description.

**Comment by shlok007** [comment]
Sample data is to be added to populate the database in development in seed.rb. This issue is just a reminder, I'll add it myself. :)

**Comment by shlok007** [comment]
It's done.We can close the issue now.

**Comment by aayusharora** [comment]
closing :+1:
